site_name: Wiki
site_url: http://127.0.0.1:8000/
repo_url: https://github.com/jruing/obsidian
repo_name: jruing/obsidian

use_directory_urls: false
theme:
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  highlightjs: true
  plugins:
  - social
  hljs_languages:
    - yaml
    - rust
    - toml
    - css
    - javascript
    - typescript
    - python
    - go
    - html
  features:
    - navigation.instant            # 即时加载
    - navigation.instant.prefetch   # 即时预取
    - navigation.instant.progress   # 进度指示器
    - navigation.instant.preview    # 全局启用即时预览
    - navigation.tracking           # 锚跟踪（类似点击后）
    - navigation.tabs               # 启用选项卡（最顶层）
    - navigation.tabs.sticky        # 粘性导航选项卡（保持可见）
    - navigation.tabs.sections      # 分段
    - navigation.expand             # 展开所有
    - navigation.path               # 导航路径（面包屑）（没效果）
    - navigation.indexes            # 节索引页
    - toc.follow                    # 锚跟随
    - navigation.top                # 返回顶部按钮
    - navigation.footer             # 启用页脚（上一页、下一页）
    - search.suggest                # 搜索建议
    - search.highlight              # 搜索高亮显示
    - search.share                  # 搜索分享
    - content.code.copy             # 代码复制
    - content.action.edit
    - navigation.prune



nav:
  - 简介:
    - 关于: readme.md
  - 开发:
    - 前端:
      - 基础三剑客:
        - javascript: 开发/前端/基础三剑客/javascript/index.md
        - 元素选择器: 开发/前端/基础三剑客/javascript/元素选择器.md
        - fetch 学习笔记: 开发/前端/基础三剑客/javascript/fetch 学习笔记.md
        - forEach数组循环: 开发/前端/基础三剑客/javascript/forEach数组循环.md
        - Javascript学习笔记-js实现拷贝复制功能: 开发/前端/基础三剑客/javascript/Javascript学习笔记-js实现拷贝复制功能.md
        - js控制台Hook: 开发/前端/基础三剑客/javascript/js控制台Hook.md
      - React:
        - React-安装: 开发/前端/React/React-安装.md
        - React-更新页面数据: 开发/前端/React/React-更新页面数据.md
        - React-列表渲染: 开发/前端/React/React-列表渲染.md
        - React-数据展示: 开发/前端/React/React-数据展示.md
        - React-条件判断: 开发/前端/React/React-条件判断.md
        - React-响应事件: 开发/前端/React/React-响应事件.md
        - React-JSX: 开发/前端/React/React-JSX.md
        - React-Props传递给组件: 开发/前端/React/React-Props传递给组件.md
      - Vue:
        - Vue3 Router路由: 开发/前端/Vue/Vue3 Router路由.md
        - Vue3+Vite项目基础环境搭建: 开发/前端/Vue/Vue3+Vite项目基础环境搭建.md
    - Golang:
      - 基础:
        - Golang学习笔记-变量: 开发/Golang/基础/Golang学习笔记-变量.md
        - Golang学习笔记-常量: 开发/Golang/基础/Golang学习笔记-常量.md
        - Golang学习笔记-判断: 开发/Golang/基础/Golang学习笔记-判断.md
        - Golang学习笔记-数据类型: 开发/Golang/基础/Golang学习笔记-数据类型.md
        - Golang学习笔记-循环: 开发/Golang/基础/Golang学习笔记-循环.md
        - Golang学习笔记-goto: 开发/Golang/基础/Golang学习笔记-goto.md
      - 进阶:
        - Golang 学习笔记-结构体与匿名结构体: 开发/Golang/进阶/Golang 学习笔记-结构体与匿名结构体.md
        - Golang 学习笔记-sqlc 代码生成: 开发/Golang/进阶/Golang 学习笔记-sqlc 代码生成.md
        - Golang 学习笔记-Viper: 开发/Golang/进阶/Golang 学习笔记-Viper.md
        - Golang学习笔记-处理HTTP请求参数: 开发/Golang/进阶/Golang学习笔记-处理HTTP请求参数.md
        - Golang学习笔记-定时任务: 开发/Golang/进阶/Golang学习笔记-定时任务.md
        - Golang学习笔记-跨平台编译: 开发/Golang/进阶/Golang学习笔记-跨平台编译.md
        - Golang学习笔记-令牌桶限流: 开发/Golang/进阶/Golang学习笔记-令牌桶限流.md
        - Golang学习笔记-自定义日志轮转及输出: 开发/Golang/进阶/Golang学习笔记-自定义日志轮转及输出.md
        - Golang学习笔记-Casbin学习笔记: 开发/Golang/进阶/Golang学习笔记-Casbin学习笔记.md
      - go-zero:
    - Java:
    - Python:
      - 基础:
        - 安装环境: 开发/Python/基础/安装环境.md
        - 函数: 开发/Python/基础/函数.md
        - 继承与多继承MRO: 开发/Python/基础/继承与多继承MRO.md
        - 类: 开发/Python/基础/类.md
        - 模块: 开发/Python/基础/模块.md
        - 判断: 开发/Python/基础/判断.md
        - 数据类型: 开发/Python/基础/数据类型.md
        - 循环: 开发/Python/基础/循环.md
        - 异常处理: 开发/Python/基础/异常处理.md
        - pathlib用法: 开发/Python/基础/pathlib用法.md
        - pydantic用法: 开发/Python/基础/pydantic用法.md
        - python日志: 开发/Python/基础/python日志.md
        - struct用法: 开发/Python/基础/struct用法.md
        - uv安装Python: 开发/Python/基础/uv安装Python.md
        - zipapp用法: 开发/Python/基础/zipapp用法.md
      - 进阶:
        - Python学习笔记-__missing__用法: 开发/Python/进阶/Python学习笔记-__missing__用法.md
        - Python学习笔记-参数类型提示: 开发/Python/进阶/Python学习笔记-参数类型提示.md
        - Python学习笔记-创建虚拟环境及配置: 开发/Python/进阶/Python学习笔记-创建虚拟环境及配置.md
        - Python学习笔记-调用dll: 开发/Python/进阶/Python学习笔记-调用dll.md
        - Python学习笔记-读取指定文件指定行: 开发/Python/进阶/Python学习笔记-读取指定文件指定行.md
        - python学习笔记-偏函数: 开发/Python/进阶/python学习笔记-偏函数.md
        - Python学习笔记-实现链式函数调用: 开发/Python/进阶/Python学习笔记-实现链式函数调用.md
        - Python学习笔记-装饰器: 开发/Python/进阶/Python学习笔记-装饰器.md
        - Python学习笔记-gc垃圾回收: 开发/Python/进阶/Python学习笔记-gc垃圾回收.md
        - Python学习笔记-grpc: 开发/Python/进阶/Python学习笔记-grpc.md
        - Python学习笔记-property和setter: 开发/Python/进阶/Python学习笔记-property和setter.md
        - Python学习笔记-Schema数据结构及类型校验: 开发/Python/进阶/Python学习笔记-Schema数据结构及类型校验.md
        - Python学习笔记-struct处理二进制数据: 开发/Python/进阶/Python学习笔记-struct处理二进制数据.md
        - Python学习笔记-with上下文管理器: 开发/Python/进阶/Python学习笔记-with上下文管理器.md
        - Python学习笔记-yield用法及优点: 开发/Python/进阶/Python学习笔记-yield用法及优点.md
        - Python学习笔记-Zipapp打包可执行文件: 开发/Python/进阶/Python学习笔记-Zipapp打包可执行文件.md
      - 爬虫:
        - 某验五子棋验证码: 开发/Python/爬虫/某验五子棋验证码.md
        - 有道翻译爬虫: 开发/Python/爬虫/有道翻译爬虫.md
        - JsRpc练习: 开发/Python/爬虫/JsRpc练习.md
        - Python selenium过图片滑块验证: 开发/Python/爬虫/Python selenium过图片滑块验证.md
        - Python爬虫-无限VM debugger解决方案: 开发/Python/爬虫/Python爬虫-无限VM debugger解决方案.md
      - 设计模式:
        - 单例模式: 开发/Python/设计模式/单例模式.md
        - 工厂模式: 开发/Python/设计模式/工厂模式.md
      - 数据分析:
        - Pandas用法: 开发/Python/数据分析/Pandas用法.md
      - 自动化:
        - playwright:
          - 目录: 开发/Python/自动化/playwright/目录.md
          - playwright安装: 开发/Python/自动化/playwright/playwright安装.md
          - playwright防自动化检测: 开发/Python/自动化/playwright/playwright防自动化检测.md
          - playwright基础: 开发/Python/自动化/playwright/playwright基础.md
          - playwright进阶: 开发/Python/自动化/playwright/playwright进阶.md
        - selenium:
          - Selenium接管浏览器: 开发/Python/自动化/selenium/Selenium接管浏览器.md
      - Web:
        - Django:
        - FastAPI:
          - 安装: 开发/Python/Web/FastAPI/安装.md
        - Flask:
  - 日常工具:
    - 基于订阅号开发属于自己的微信消息通知: 日常工具/基于订阅号开发属于自己的微信消息通知.md
    - Frp 内网穿透搭建: 日常工具/Frp 内网穿透搭建.md
    - jookdb重置试用期: 日常工具/jookdb重置试用期.md
    - RustDesk 私有化部署: 日常工具/RustDesk 私有化部署.md
    - task任务构建工具: 日常工具/task任务构建工具.md
    - UPX使用方法: 日常工具/UPX使用方法.md
    - Wiki.js 安装: 日常工具/Wiki.js 安装.md
    - win10右键添加复制文件绝对路径: 日常工具/win10右键添加复制文件绝对路径.md
  - 数据库:
    - MySQL:
      - Mysql57绿色版安装: 数据库/MySQL/Mysql57绿色版安装.md
    - PostgreSQL:
      - postgres安装: 数据库/PostgreSQL/postgres安装.md
      - Postgres学习笔记-Sequence自增序列: 数据库/PostgreSQL/Postgres学习笔记-Sequence自增序列.md
    - Redis:
      - 安装及基础: 数据库/Redis/安装及基础.md
      - Redis7.XCentos集群搭建: 数据库/Redis/Redis7.XCentos集群搭建.md
  - 运维:
    - Neo4j 实现一个简单的CMDB管理平台: 运维/Neo4j 实现一个简单的CMDB管理平台.md
    - SSH隧道代理: 运维/SSH隧道代理.md
    - Minio:
      - 环境搭建与安装: 运维/Minio/环境搭建与安装.md
    - 监控:
      - Uptime-kuma 监控: 运维/监控/Uptime-kuma 监控.md
      - 日志监控:
        - 基于Grafana+Loki+Promatil搭建日志分析平台: 运维/监控/日志监控/基于Grafana+Loki+Promatil搭建日志分析平台.md
      - Prometheus:
        - Prometheus学习笔记-安装: 运维/监控/Prometheus/Prometheus学习笔记-安装.md
        - Prometheus学习笔记-安装blackbox_exporter: 运维/监控/Prometheus/Prometheus学习笔记-安装blackbox_exporter.md
        - Prometheus学习笔记-安装Node_exporter: 运维/监控/Prometheus/Prometheus学习笔记-安装Node_exporter.md
        - Prometheus学习笔记-告警规则配置: 运维/监控/Prometheus/Prometheus学习笔记-告警规则配置.md
        - Prometheus学习笔记-监控docker容器: 运维/监控/Prometheus/Prometheus学习笔记-监控docker容器.md
        - Prometheus学习笔记-配置文件字段解析: 运维/监控/Prometheus/Prometheus学习笔记-配置文件字段解析.md
        - Prometheus学习笔记-设置Basic_auth登录校验: 运维/监控/Prometheus/Prometheus学习笔记-设置Basic_auth登录校验.md
        - Prometheus学习笔记-file_sd_config: 运维/监控/Prometheus/Prometheus学习笔记-file_sd_config.md
        - Prometheus学习笔记-Grafana可视化: 运维/监控/Prometheus/Prometheus学习笔记-Grafana可视化.md
        - Prometheus学习笔记-Label标签: 运维/监控/Prometheus/Prometheus学习笔记-Label标签.md
    - 进程管理:
      - Supervisor 学习笔记: 运维/进程管理/Supervisor 学习笔记.md
    - 容器化:
      - Docker:
        - 环境搭建与安装: 运维/容器化/Docker/环境搭建与安装.md
        - Docker Swarm 学习笔记: 运维/容器化/Docker/Docker Swarm 学习笔记.md
        - Docker-Compose安装: 运维/容器化/Docker/Docker-Compose安装.md
        - Docker学习笔记-安装Nginx及实践应用: 运维/容器化/Docker/Docker学习笔记-安装Nginx及实践应用.md
        - Docker学习笔记-多阶段构建学习笔记: 运维/容器化/Docker/Docker学习笔记-多阶段构建学习笔记.md
        - Docker学习笔记-构建私有镜像仓库: 运维/容器化/Docker/Docker学习笔记-构建私有镜像仓库.md
        - Docker学习笔记-镜像体积缩小: 运维/容器化/Docker/Docker学习笔记-镜像体积缩小.md
        - Docker学习笔记-容器镜像导入导出: 运维/容器化/Docker/Docker学习笔记-容器镜像导入导出.md
        - Docker学习笔记-在线安装教程: 运维/容器化/Docker/Docker学习笔记-在线安装教程.md
        - Docker学习笔记-redis部署: 运维/容器化/Docker/Docker学习笔记-redis部署.md
      - Kubernetes:
        - 目录: 运维/容器化/Kubernetes/目录.md
        - kubernetes学习笔记-安装: 运维/容器化/Kubernetes/kubernetes学习笔记-安装.md
        - kubernetes学习笔记-ConfigMap: 运维/容器化/Kubernetes/kubernetes学习笔记-ConfigMap.md
        - kubernetes学习笔记-Deployment: 运维/容器化/Kubernetes/kubernetes学习笔记-Deployment.md
        - kubernetes学习笔记-helm: 运维/容器化/Kubernetes/kubernetes学习笔记-helm.md
        - kubernetes学习笔记-Ingress: 运维/容器化/Kubernetes/kubernetes学习笔记-Ingress.md
        - kubernetes学习笔记-namespace: 运维/容器化/Kubernetes/kubernetes学习笔记-namespace.md
        - kubernetes学习笔记-Pod: 运维/容器化/Kubernetes/kubernetes学习笔记-Pod.md
        - kubernetes学习笔记-ReplicaSet: 运维/容器化/Kubernetes/kubernetes学习笔记-ReplicaSet.md
        - kubernetes学习笔记-Service: 运维/容器化/Kubernetes/kubernetes学习笔记-Service.md
    - Caddy:
      - caddy安装: 运维/Caddy/caddy安装.md
      - caddy简介: 运维/Caddy/caddy简介.md
      - caddy静态文件: 运维/Caddy/caddy静态文件.md
      - caddy实战-反向代理: 运维/Caddy/caddy实战-反向代理.md
      - caddy实战-黑白名单: 运维/Caddy/caddy实战-黑白名单.md
      - caddy实战-静态站点: 运维/Caddy/caddy实战-静态站点.md
      - caddy实战-basicauth授权: 运维/Caddy/caddy实战-basicauth授权.md
      - caddy手册: 运维/Caddy/caddy手册.md
    - Jenkins:
      - 部署Github项目: 运维/Jenkins/部署Github项目.md
      - 环境搭建与安装: 运维/Jenkins/环境搭建与安装.md
      - 目录: 运维/Jenkins/目录.md
      - Freestyle Job: 运维/Jenkins/Freestyle Job.md
      - Jenkinsfile: 运维/Jenkins/Jenkinsfile.md
      - Pipline: 运维/Jenkins/Pipline.md
      - Trigger: 运维/Jenkins/Trigger.md
    - Nginx:
      - 环境搭建与安装: 运维/Nginx/环境搭建与安装.md
      - Nginx学习笔记-部署静态页面实践: 运维/Nginx/Nginx学习笔记-部署静态页面实践.md
      - Nginx学习笔记-负载均衡配置: 运维/Nginx/Nginx学习笔记-负载均衡配置.md
      - Nginx学习笔记-黑名单-白名单: 运维/Nginx/Nginx学习笔记-黑名单-白名单.md
      - Nginx学习笔记-解决前端后端跨域: 运维/Nginx/Nginx学习笔记-解决前端后端跨域.md
      - Nginx学习笔记-配置文件详解: 运维/Nginx/Nginx学习笔记-配置文件详解.md
      - Nginx学习笔记-图片防盗链: 运维/Nginx/Nginx学习笔记-图片防盗链.md
      - Nginx学习笔记-auth_basic认证: 运维/Nginx/Nginx学习笔记-auth_basic认证.md
      - Nginx学习笔记-Centos 7 安装Nginx: 运维/Nginx/Nginx学习笔记-Centos 7 安装Nginx.md
      - Nginx学习笔记-Nginx简介: 运维/Nginx/Nginx学习笔记-Nginx简介.md
    - Serverless:
      - ServerLess学习笔记-完整指南: 运维/Serverless/ServerLess学习笔记-完整指南.md
    - Traefik:
      - Traefik学习笔记-安装: 运维/Traefik/Traefik学习笔记-安装.md
      - Traefik学习笔记-概念详解（基于 Docker Labels 配置）: 运维/Traefik/Traefik学习笔记-概念详解（基于 Docker Labels 配置）.md
      - Traefik学习笔记-重定向配置: 运维/Traefik/Traefik学习笔记-重定向配置.md
      - Traefik学习笔记-自定义中间件: 运维/Traefik/Traefik学习笔记-自定义中间件.md
  - AI:
    - Claude Code+Claude Code Router: AI/Claude Code+Claude Code Router.md
    - Docker安装OneAPI: AI/Docker安装OneAPI.md
    - Gemini-cli: AI/Gemini-cli.md
    - 提示词:
      - 八荣八耻: AI/提示词/八荣八耻.md
      - 单词记忆助手: AI/提示词/单词记忆助手.md
      - 豆包-生成架构图: AI/提示词/豆包-生成架构图.md
      - 豆包-丝控: AI/提示词/豆包-丝控.md
      - 豆包-KFC图片: AI/提示词/豆包-KFC图片.md
      - 反向PUA: AI/提示词/反向PUA.md
      - 归纳总结: AI/提示词/归纳总结.md
      - 黑白系图片生成: AI/提示词/黑白系图片生成.md
      - 互动式零基础教学: AI/提示词/互动式零基础教学.md
      - 可视化网页: AI/提示词/可视化网页.md
      - 猫娘: AI/提示词/猫娘.md
      - 叛逆小子: AI/提示词/叛逆小子.md
      - 人类作者模拟器: AI/提示词/人类作者模拟器.md
      - 天气卡片: AI/提示词/天气卡片.md
      - 源文档到SVG幻灯片生成器: AI/提示词/源文档到SVG幻灯片生成器.md
      - Banana提示词-文章变成卡通信息图: AI/提示词/Banana提示词-文章变成卡通信息图.md
      - deepseekR1增强: AI/提示词/deepseekR1增强.md
      - gork-涩涩: AI/提示词/gork-涩涩.md
      - Graphviz工具: AI/提示词/Graphviz工具.md
      - RooCode角色提示词: AI/提示词/RooCode角色提示词.md
    - AIAgent:
      - AnythingLLM+Ollama搭建本地知识库: AI/AIAgent/AnythingLLM+Ollama搭建本地知识库.md
      - LlamaIndex-Agent关联数据库: AI/AIAgent/LlamaIndex-Agent关联数据库.md
      - Llamaindex-Agent自然语言查询数据库: AI/AIAgent/Llamaindex-Agent自然语言查询数据库.md
    - Coze:
      - 安装 Coze Studio: AI/Coze/安装 Coze Studio.md
    - Eino:
    - Google ADK:
      - Google ADK安装: AI/Google ADK/Google ADK安装.md
      - Google ADK实现简历打分助手: AI/Google ADK/Google ADK实现简历打分助手.md
    - MCP:
      - MCP学习笔记-查询主机资源使用情况: AI/MCP/MCP学习笔记-查询主机资源使用情况.md
      - MCP学习笔记-从0到1: AI/MCP/MCP学习笔记-从0到1.md
      - MCP学习笔记-天气预报: AI/MCP/MCP学习笔记-天气预报.md
  - Linux:
    - 基础:
      - linux学习笔记-搭建FTP服务: Linux/基础/linux学习笔记-搭建FTP服务.md
      - linux学习笔记-服务器基础信息查询脚本: Linux/基础/linux学习笔记-服务器基础信息查询脚本.md
      - linux学习笔记-更换镜像源: Linux/基础/linux学习笔记-更换镜像源.md
      - linux学习笔记-免密登录: Linux/基础/linux学习笔记-免密登录.md
      - linux学习笔记-终端美化-zsh: Linux/基础/linux学习笔记-终端美化-zsh.md
      - linux学习笔记-awk: Linux/基础/linux学习笔记-awk.md
      - linux学习笔记-cgroup(二): Linux/基础/linux学习笔记-cgroup(二).md
      - linux学习笔记-cgroup(一): Linux/基础/linux学习笔记-cgroup(一).md
      - linux学习笔记-grep: Linux/基础/linux学习笔记-grep.md
      - linux学习笔记-iptables: Linux/基础/linux学习笔记-iptables.md
      - linux学习笔记-jq: Linux/基础/linux学习笔记-jq.md
      - linux学习笔记-nano用法: Linux/基础/linux学习笔记-nano用法.md
      - linux学习笔记-rsync数据同步: Linux/基础/linux学习笔记-rsync数据同步.md
      - linux学习笔记-screen: Linux/基础/linux学习笔记-screen.md
      - linux学习笔记-sed手册: Linux/基础/linux学习笔记-sed手册.md
      - linux学习笔记-SSH隧道代理: Linux/基础/linux学习笔记-SSH隧道代理.md
      - linux学习笔记-sudo: Linux/基础/linux学习笔记-sudo.md
      - linux学习笔记-Systemd: Linux/基础/linux学习笔记-Systemd.md
      - linux学习笔记-tmux: Linux/基础/linux学习笔记-tmux.md
      - linux学习笔记-Ubuntu常用软件安装: Linux/基础/linux学习笔记-Ubuntu常用软件安装.md
      - linux学习笔记-ufw: Linux/基础/linux学习笔记-ufw.md